# Generated by Django 2.2.1 on 2019-05-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_images/%Y/%m/%d/'),
        ),
    ]
