# Generated by Django 2.2.1 on 2019-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190503_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_images/%Y/%m/%d'),
        ),
    ]
