# Generated by Django 2.2.1 on 2019-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_confirmed',
            new_name='is_confirmed_by_customer',
        ),
        migrations.AddField(
            model_name='order',
            name='is_confirmed_by_owner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
