# Generated by Django 2.2.1 on 2019-05-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190508_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_confirmed_by_customer',
            new_name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_confirmed_by_owner',
        ),
    ]
