# Generated by Django 2.2.1 on 2019-05-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('thr', 'থ্রিলার'), ('com', 'কমেডি'), ('oth', 'অন্যান্য')], default='oth', max_length=3)),
            ],
        ),
    ]
