# Generated by Django 2.2.1 on 2019-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190503_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='detaile',
            field=models.TextField(default=123, max_length=1024),
            preserve_default=False,
        ),
    ]
