# Generated by Django 2.2.1 on 2019-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190503_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
