# Generated by Django 2.2.1 on 2019-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190503_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='detaile',
            field=models.TextField(choices=[('en', 'English'), ('bn', 'Bengali')], max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
