# Generated by Django 2.2.1 on 2019-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190504_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='detaile',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.CharField(max_length=255),
        ),
    ]
