# Generated by Django 2.2.1 on 2019-05-04 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190504_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
