# Generated by Django 2.2.1 on 2019-05-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190504_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_award_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('other', 'বিবিধ'), ('translated_books', 'অনুবাদ'), ('law_and_justice', 'আইন ও বিচার'), ('self_help_and_meditation', 'আত্ম-উন্নয়ন ও মেডিটেশন'), ('university_books', 'ইউনিভার্সিটি'), ('engineering_books', 'ইঞ্জিনিয়ারিং'), ('history_and_tradition', 'ইতিহাস ও ঐতিহ্য'), ('in_stock_books', 'ইন স্টক বুকস'), ('english_language', 'ইংরেজি ভাষার বই'), ('novel', 'উপন্যাস'), ('comics_and_graphic_novels', 'কমিকস, নকশা ও ছবির গল্প'), ('computer_and_internet', 'কম্পিউটার, ইন্টারনেট, ফ্রিল্যান্সিং ও আউটসোর্সিং'), ('agriculture', 'কৃষি ও কৃষক'), ('sports_and_games', 'খেলাধুলা'), ('media_journalism_&_reportig', 'গণমাধ্যম ও সাংবাদিকতা'), ('math_science_and_tech', 'গণিত, বিজ্ঞান ও প্রযুক্তি'), ('story_books', 'গল্প'), ('rhymes_poems_recitation', 'ছড়া, কবিতা ও আবৃত্তি'), ('biography_memory_intterview', 'জীবনী, স্মৃতিচারণ ও সাক্ষাৎকার'), ('painting_design_photography', 'ড্রয়িং, পেইন্টিং ডিজাইন ও ফটোগ্রাফি'), ('philosophy', 'দর্শন'), ('religious_books', 'ধর্মীয় বই'), ('drama', 'নাটকের বই'), ('nature_and_outdoor', 'পরিবেশ ও প্রকৃতি'), ('west_bengal_books', 'পশ্চিমবঙ্গের বই'), ('award_wining', 'পুরস্কারপ্রাপ্ত বই'), ('professional_journal_referance', 'প্রফেশনাল, জার্নাল ও রেফারেন্স'), ('article', 'প্রবন্ধ'), ('prcessing', 'প্রসেসিং'), ('animals_animal_kingdom', 'প্রাণী ও জীবজগৎ'), ('pre_order', 'প্রি অর্ডার'), ('fashion_family', 'ফ্যাশন, রূপচর্চা ও পরিবার'), ('bangladesh', 'বাংলাদেশ'), ('humour_entertainment', 'ব্যঙ্গ ও রম্যরচনা'), ('business_invest_economics', 'ব্যবসা, বিনিয়োগ ও অর্থনীতি'), ('exam_preparation_guide', 'ভর্তি, নিয়োগ ও প্রস্তুতি পরীক্ষা'), ('language_and_dictionary', 'ভাষা ও অভিধান'), ('travel', 'ভ্রমণ ও প্রবাস'), ('liberation_of_bd', 'মুক্তিযুদ্ধ'), ('medical_books', 'মেডিকেল')], max_length=32),
        ),
    ]
