# Generated by Django 2.2.1 on 2019-05-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190504_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detaile',
            new_name='details',
        ),
    ]
