# Generated by Django 2.2.1 on 2019-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190505_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
    ]
