# Generated by Django 2.2.1 on 2019-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_publish_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_unit',
            field=models.IntegerField(default=0),
        ),
    ]
