# Generated by Django 2.2.1 on 2019-05-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20190507_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_year',
            field=models.CharField(max_length=8),
        ),
    ]
